version: '3'
services:
  mysqldb_customer_inventories:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: legacy
      MYSQL_DATABASE: customer_inventory
    ports:
      - "33001:3306"
    volumes:
      - "./config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
      - "./mysql-dump:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: legacy
    ports:
      - "34001:80"
